# Generated by Django 5.0.6 on 2024-05-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnotatedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("class_name", models.CharField(max_length=100)),
                ("status", models.CharField(default="pending", max_length=20)),
            ],
        ),
    ]
