# Generated by Django 5.0.6 on 2024-05-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_annotation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploaded_images/")),
                ("class_name", models.CharField(max_length=255)),
                ("status", models.CharField(default="pending", max_length=50)),
            ],
        ),
    ]
