# Generated by Django 5.0.6 on 2024-05-08 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("image_annotation", "0002_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
