# Generated by Django 5.0.6 on 2024-05-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_annotation", "0003_delete_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotatedimage",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
